CREATE DATABASE BANCODEDADOS;

USE BANCODEDADOS;

CREATE TABLE MARCA(
    IDMARCA INTEGER PRIMARY KEY,
    nome TEXT NOT NULL

);

CREATE TABLE TIPOCARRO(
    IDTIPOCARRO INTEGER PRIMARY KEY,
    nome TEXT NOT NULL,
    funcao TEXT,
    ID_MARCA INTEGER,
    FOREIGN KEY(ID_MARCA)
    REFERENCES MARCA(IDMARCA)

);

CREATE TABLE CARRO(
    IDCARRO INTEGER PRIMARY KEY,
    placa TEXT NOT NULL,
    ID_TIPOCARRO INTEGER,
    FOREIGN KEY(ID_TIPOCARRO)
    REFERENCES TIPOCARRO(IDTIPOCARRO) 

);

CREATE TABLE TIPOPRODUTO(
    IDTIPOPRODUTO INTEGER PRIMARY KEY,
    nome TEXT NOT NULL,
    tipo TEXT NOT NULL CHECK (tipo IN ('Fluido', 'Peca')) 

);

CREATE TABLE PRODUTO(
    IDPRODUTO INTEGER PRIMARY KEY,
    quantidade INT NOT NULL,
    numero TEXT NOT NULL,
    ID_MARCA INTEGER,
    FOREIGN KEY(ID_MARCA)
    REFERENCES MARCA(IDMARCA)
    
);

CREATE TABLE COMPATIBILIDADE(
    ID_PRODUTO INTEGER,
    ID_CARRO INTEGER,
    FOREIGN KEY(ID_PRODUTO)
    REFERENCES PRODUTO(IDPRODUTO),
    FOREIGN KEY(ID_CARRO)
    REFERENCES CARRO(IDCARRO)

);

CREATE TABLE REGISTRO(
    IDREGISTRO INTEGER PRIMARY KEY,
    dataCompra TEXT NOT NULL,
    localCompra TEXT NOT NULL,
    quantidadeComprada INT NOT NULL,
    ID_PRODUTO INTEGER,
    FOREIGN KEY(ID_PRODUTO)
    REFERENCES PRODUTO(IDPRODUTO)

);

CREATE TABLE FUNCIARIO(
    IDFUNCIONARIO INTEGER PRIMARY KEY,
    nome TEXT NOT NULL

);

CREATE TABLE MANUTENCAO(
    IDMANUTENCAO INTEGER PRIMARY KEY,
    dataManutencao TEXT NOT NULL,
    ID_CARRO INTEGER,
    ID_PRODUTO INTEGER,
    ID_REGISTRO INTEGER,
    FOREIGN KEY(ID_CARRO)
    REFERENCES CARRO(IDCARRO),
    FOREIGN KEY(ID_PRODUTO)
    REFERENCES PRODUTO(IDPRODUTO),
    FOREIGN KEY(ID_REGISTRO)
    REFERENCES REGISTO(IDREGISTRO)

);

CREATE TABLE MENSAGEM(
    IDMENSAGEM INTEGER PRIMARY KEY,
    conteudo TEXT NOT NULL,
    ID_MANUTENCAO INTEGER,
    FOREIGN KEY(ID_MANUTENCAO)
    REFERENCES MANUTENCAO(IDMANUTENCAO)

);